/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6p4O2s57jqo
 */
import { Checkbox } from "@/components/ui/checkbox";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "@/components/ui/command";
import { Label } from "@/components/ui/label";

interface IProps {
  options: string[];
}

export function CheckboxGroup(props: IProps) {
  const { options } = props;
  return (
    <div>
      <Command>
        <CommandInput className="h-9" placeholder="Filter Options" />
        <CommandEmpty>No items found.</CommandEmpty>
        <CommandGroup className="overflow-y-auto max-h-40">
          {options.map((option: string, idx: number) => (
            <CommandItem key={idx.toString()}>
              <Checkbox id={idx.toString()} name="items" />
              <Label
                className="text-sm font-normal px-2"
                htmlFor={idx.toString()}
              >
                {option}
              </Label>
            </CommandItem>
          ))}
        </CommandGroup>
      </Command>
    </div>
  );
}
